apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eventStream.name }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.eventStream.name }}
  ports:
    - name: http
      port: {{ .Values.eventStream.port }}
