globals:
  host: evestidor.com.br
  configMap: globals

ui:
  image: evestidor/ui:master
  name: evestidor-ui
  port: 80
  targetPort: 8000
  replicas: 1
  configMap: ui

apiGateway:
  image: evestidor/api-gateway:master
  name: evestidor-api-gateway
  port: 80
  targetPort: 8000
  replicas: 1

eventStream:
  image: evestidor/event-stream:master
  name: evestidor-event-stream
  port: 5672
  replicas: 1

stockManager:
  image: evestidor/stock-manager:master
  name: evestidor-stock-manager
  port: 80
  targetPort: 8000
  replicas: 1
  configMap: stock-manager

stockPrice:
  image: evestidor/stock-price-simulator:master
  name: evestidor-stock-price-simulator
  port: 80
  targetPort: 8000
  replicas: 1
