apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.apiGateway.name }}
spec:
  rules:
    - host: {{ .Values.globals.host }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ .Values.apiGateway.name }}
              servicePort: {{ .Values.apiGateway.port }}
