apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.targetPort }}
