apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eventStream.name }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.eventStream.name }}
  ports:
    - name: http
      port: {{ .Values.eventStream.port }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.eventStream.name }}
spec:
  replicas: {{ .Values.eventStream.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.eventStream.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.eventStream.name }}
    spec:
      containers:
        - name: {{ .Values.eventStream.name }}
          image: {{ .Values.eventStream.image }}
