apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockManager.name }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.stockManager.name }}
  ports:
    - name: http
      port: {{ .Values.stockManager.port }}
      targetPort: {{ .Values.stockManager.targetPort }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockManager.name }}
spec:
  replicas: {{ .Values.stockManager.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.stockManager.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.stockManager.name }}
    spec:
      containers:
        - name: {{ .Values.stockManager.name }}
          image: {{ .Values.stockManager.image }}
