apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"evestidor-ui"}}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.ui.port }}
    protocol: TCP
    targetPort: {{ .Values.ui.targetPort }}
