apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ui.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api
spec:
  rules:
    - host: {{ .Values.globals.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.ui.name }}
              servicePort: {{ .Values.ui.port }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.ui.name }}
  ports:
    - name: http
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.targetPort }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
        - name: {{ .Values.ui.name }}
          image: {{ .Values.ui.image }}
