apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockPrice.name }}
spec:
  replicas: {{ .Values.stockPrice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.stockPrice.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.stockPrice.name }}
    spec:
      - name: init-migrate
          image: {{ .Values.stockManager.image }}
          command: python manage.py migrate
      containers:
        - name: {{ .Values.stockPrice.name }}
          image: {{ .Values.stockPrice.image }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.globals.configMap }}
