apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockPrice.name }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.stockPrice.name }}
  ports:
    - name: http
      port: {{ .Values.stockPrice.port }}
      targetPort: {{ .Values.stockPrice.targetPort }}
