apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
        - name: {{ .Values.ui.name }}
          image: {{ .Values.ui.image }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.globals.configMap }}
            - configMapRef:
                name: {{ .Values.ui.configMap }}
