apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ui.name }}
spec:
  rules:
    - host: {{ .Values.globals.host }}
      http:
        paths:
          - path: /app
            backend:
              serviceName: {{ .Values.ui.name }}
              servicePort: {{ .Values.ui.port }}
