apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ui.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.globals.host }}
      http:
        paths:
          - path: /app(/|$)(.*)
            backend:
              serviceName: {{ .Values.ui.name }}
              servicePort: {{ .Values.ui.port }}
