apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockManager.name }}-consumer
spec:
  replicas: {{ .Values.stockManager.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.stockManager.name }}-consumer

  template:
    metadata:
      labels:
        app: {{ .Values.stockManager.name }}-consumer
    spec:
      containers:
        - name: {{ .Values.stockManager.name }}-consumer
          image: {{ .Values.stockManager.image }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.globals.configMap }}
            - configMapRef:
                name: {{ .Values.stockManager.configMap }}
