apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}

spec:
  selector:
    app: {{ .Values.serviceName }}

  ports:
    - name: http
      port: 8000
      targetPort: 80
  type: LoadBalancer
