apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}

spec:
  type: ClusterIP

  selector:
    app: {{ .Values.service.name }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
