apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}

spec:
  type: ClusterIP

  selector:
    app: {{ .Values.serviceName }}

  ports:
    - name: http
      port: {{ .Values.servicePort }}
